//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEX.DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class integral_smscontentpush_mt_messages
    {
        public long id { get; set; }
        public string category_ids { get; set; }
        public Nullable<long> content_id { get; set; }
        public Nullable<int> app_id { get; set; }
        public string shortcode { get; set; }
        public string message { get; set; }
        public Nullable<int> isUnicode { get; set; }
        public Nullable<bool> isFlash { get; set; }
        public string url { get; set; }
        public Nullable<int> login_id { get; set; }
        public string hash { get; set; }
        public string datetime_string { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
        public string flag { get; set; }
    }
}
