//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDEX.DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class receive
    {
        public int myid { get; set; }
        public string sender { get; set; }
        public string prefix { get; set; }
        public string message { get; set; }
        public string scode { get; set; }
        public string dates { get; set; }
        public string times { get; set; }
        public string flag { get; set; }
    }
}
