//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IDEX.IDEXProxyWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ContentSoap", Namespace="http://tempuri.org/")]
    public partial class Content : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback UploadNormalTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadSMSLink5OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Content() {
            this.Url = global::IDEX.Properties.Settings.Default.IDEX_IDEXProxyWS_Content;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event UploadNormalTextCompletedEventHandler UploadNormalTextCompleted;
        
        /// <remarks/>
        public event UploadSMSLink5CompletedEventHandler UploadSMSLink5Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadNormalText", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Result UploadNormalText(string User, string Password, string LinkID, string ChannelID, string Data) {
            object[] results = this.Invoke("UploadNormalText", new object[] {
                        User,
                        Password,
                        LinkID,
                        ChannelID,
                        Data});
            return ((Result)(results[0]));
        }
        
        /// <remarks/>
        public void UploadNormalTextAsync(string User, string Password, string LinkID, string ChannelID, string Data) {
            this.UploadNormalTextAsync(User, Password, LinkID, ChannelID, Data, null);
        }
        
        /// <remarks/>
        public void UploadNormalTextAsync(string User, string Password, string LinkID, string ChannelID, string Data, object userState) {
            if ((this.UploadNormalTextOperationCompleted == null)) {
                this.UploadNormalTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadNormalTextOperationCompleted);
            }
            this.InvokeAsync("UploadNormalText", new object[] {
                        User,
                        Password,
                        LinkID,
                        ChannelID,
                        Data}, this.UploadNormalTextOperationCompleted, userState);
        }
        
        private void OnUploadNormalTextOperationCompleted(object arg) {
            if ((this.UploadNormalTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadNormalTextCompleted(this, new UploadNormalTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadSMSLink5", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Response UploadSMSLink5(string User, string Password, string KEY, string LinkID, string ChannelID, SMSFileObjects Files) {
            object[] results = this.Invoke("UploadSMSLink5", new object[] {
                        User,
                        Password,
                        KEY,
                        LinkID,
                        ChannelID,
                        Files});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void UploadSMSLink5Async(string User, string Password, string KEY, string LinkID, string ChannelID, SMSFileObjects Files) {
            this.UploadSMSLink5Async(User, Password, KEY, LinkID, ChannelID, Files, null);
        }
        
        /// <remarks/>
        public void UploadSMSLink5Async(string User, string Password, string KEY, string LinkID, string ChannelID, SMSFileObjects Files, object userState) {
            if ((this.UploadSMSLink5OperationCompleted == null)) {
                this.UploadSMSLink5OperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadSMSLink5OperationCompleted);
            }
            this.InvokeAsync("UploadSMSLink5", new object[] {
                        User,
                        Password,
                        KEY,
                        LinkID,
                        ChannelID,
                        Files}, this.UploadSMSLink5OperationCompleted, userState);
        }
        
        private void OnUploadSMSLink5OperationCompleted(object arg) {
            if ((this.UploadSMSLink5Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadSMSLink5Completed(this, new UploadSMSLink5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Result {
        
        private string mAPIDField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string MAPID {
            get {
                return this.mAPIDField;
            }
            set {
                this.mAPIDField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Response {
        
        private string mAPIDField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string MAPID {
            get {
                return this.mAPIDField;
            }
            set {
                this.mAPIDField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FileObject {
        
        private byte[] fileBinaryField;
        
        private string filenameField;
        
        private string fileEXTField;
        
        private string message1Field;
        
        private string message2Field;
        
        private string message3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileBinary {
            get {
                return this.fileBinaryField;
            }
            set {
                this.fileBinaryField = value;
            }
        }
        
        /// <remarks/>
        public string Filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        public string FileEXT {
            get {
                return this.fileEXTField;
            }
            set {
                this.fileEXTField = value;
            }
        }
        
        /// <remarks/>
        public string Message1 {
            get {
                return this.message1Field;
            }
            set {
                this.message1Field = value;
            }
        }
        
        /// <remarks/>
        public string Message2 {
            get {
                return this.message2Field;
            }
            set {
                this.message2Field = value;
            }
        }
        
        /// <remarks/>
        public string Message3 {
            get {
                return this.message3Field;
            }
            set {
                this.message3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SMSFileObjects {
        
        private string jSONField;
        
        private System.DateTime dateToSendField;
        
        private FileObject[] filesField;
        
        /// <remarks/>
        public string JSON {
            get {
                return this.jSONField;
            }
            set {
                this.jSONField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateToSend {
            get {
                return this.dateToSendField;
            }
            set {
                this.dateToSendField = value;
            }
        }
        
        /// <remarks/>
        public FileObject[] Files {
            get {
                return this.filesField;
            }
            set {
                this.filesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void UploadNormalTextCompletedEventHandler(object sender, UploadNormalTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadNormalTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadNormalTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void UploadSMSLink5CompletedEventHandler(object sender, UploadSMSLink5CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadSMSLink5CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadSMSLink5CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591